In [1]:
exomeSize=3e7;
mutationRate=1e-6;
ploidy=2;
resistantAlleles=1;
populationSize=25;
passageInterval=72;
passageFraction=0.1;
nPasages=10;
doublingTimeNormal=21;
doublingTimeTreated=75;
doublingTimeResistant=30;

In [2]:
import numpy as np;
doublingTimes = np.full((populationSize), doublingTimeTreated);
cellNumbers = np.full((populationSize), 1);

In [3]:
doublingTimes

array([75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75,
       75, 75, 75, 75, 75, 75, 75, 75])

In [4]:
doublingTimes[0]=doublingTimeResistant;

In [5]:
doublingTimes

array([30, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75,
       75, 75, 75, 75, 75, 75, 75, 75])

In [6]:
cellNumbers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [7]:
def grow(t, cellN, doubleT):
    return np.int64( np.fix( np.multiply(cellN, np.exp2( np.divide(t, doubleT) )) ) )

In [8]:
grow(128, cellNumbers, doublingTimes)

array([19,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3])

In [9]:
def passage(p, cellN):
    return np.random.binomial(cellN, p)

In [10]:
passage(0.1, np.multiply(1000, cellNumbers))

array([103, 106, 105, 106,  86, 100,  82,  93,  93, 101, 108, 101,  92,
       104, 101,  95, 108, 119,  90,  98,  96,  91, 118,  89,  87])

In [11]:
np.__version__

'1.13.3'

In [94]:
nSimRuns = 100
simRuns = []
nPassages = 20;

for r in range(nSimRuns):
    cellNumbers = np.full((populationSize), 1);
    nResistantCells = [cellNumbers[0]]
    for i in range(nPassages):
        cellNumbers = passage(passageFraction, 
                              grow(passageInterval, cellNumbers, doublingTimes))
        nResistantCells.append( cellNumbers[0] )
    simRuns.append( nResistantCells )

In [95]:
nResistantCells

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [96]:
simRuns

[[1, 1, 1, 2, 3, 5, 6, 2, 1, 1, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0,

In [116]:
def runSimulation(nRuns):
    simRuns = []
    
    cellNumbers = np.full((populationSize), 1)
    doublingTimes =  np.full((populationSize), doublingTimeTreated)
    
    for run in range(nRuns):
        cellNumbers = np.full((populationSize), 1)
        doublingTimes =  np.full((populationSize), doublingTimeTreated)
        doublingTimes[0] = doublingTimeResistant
        resistantCells = [ cellNumbers[0] ]
        
        for psg in range(nPassages):
            cellNumbers = np.int64(np.floor( np.multiply(cellNumbers, np.exp2( np.divide(passageInterval, doublingTimes) ))))
            cellNumbers = np.random.binomial( cellNumbers, passageFraction)
            resistantCells.append( cellNumbers[0] )
            if cellNumbers[0] == 0:
                break;
    
        simRuns.append( resistantCell )
        
    return simRuns

In [117]:
runSimulation(10)

[[1, 1, 1, 1, 1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 1, 0],
 [1, 0],
 [1, 0],
 [1, 1, 0],
 [1, 0],
 [1, 1, 0]]

In [118]:
a = np.full((5), 1)

In [119]:
a

array([1, 1, 1, 1, 1])

In [120]:
np.reshape(a, (6))

ValueError: cannot reshape array of size 5 into shape (6,)